package ownExceptions;

public class MultiplyByThreeException extends Exception{

}
